version: "3"

services:

  app:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=60

  redis:
    image: "redis:alpine"

